
const DELETE_POST="DELETE_POST";
const EDIT_POST="EDIT_POST";
const ADD_POST="ADD_POST";
const FETCH_POST="FETCH_POST";
const LIKE="LIKE";
const ADD_COMMENT="ADD_COMMENT";
const DELETE_COMMENT="DELETE_COMMENT"
